- platform: blockchain
  addresses:
    - !secret bitcoin_address1

- platform: bitcoin
  display_options:
    - exchangerate

- platform: etherscan
  address: !secret ether_address1
  name: MyEteherWallet

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: yr

- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800
  command: !secret ssl_command

- platform: emoncms
  api_key: !secret emoncms_read
  url: https://emoncms.org
  id: 1

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: disk_use_percent
      arg: /home/homeassistant/.homeassistant
