Vacation:
  entities:
    - input_boolean.vacation_mode

Automation:
  entities:
    - automation.nas_notification
    - automation.nodemcu_notification
    - automation.sunrise
    - automation.sunset
    - automation.temperature_night
    - automation.temperature_weekdays_high
    - automation.temperature_weekdays_low
    - automation.temperature_weekend_high

Automation_view:
  view: yes
  icon: mdi:home-automation
  name: Automation
  entities:
    - group.automation
    - group.vacation
